http:
  port: ${PORT:-8080}
  host: ${HOST:-localhost}
admin:
  port: 9876
  host: localhost
apiEndpoints:
  products:
    paths: 
      - '/products'
      - '/products/:id'
  product_reviews:
    paths: 
      - '/products/:id/reviews'
serviceEndpoints:
  products:
    url: 'http://product:5000'
  product_reviews:
    url: 'http://product-review:6000'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  productsPipeline:
    apiEndpoints:
      - products
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: products 
              changeOrigin: true
  productReviewsPipeline:
    apiEndpoints:
      - product_reviews
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: product_reviews 
              changeOrigin: true
